//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fishing2._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class Active
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Active()
        {
            this.Fishing = new HashSet<Fishing>();
        }
    
        public int ID_Active { get; set; }
        public int Number { get; set; }
        public System.DateTime DateAdd { get; set; }
        public string NameActive { get; set; }
        public string Category { get; set; }
        public double Price { get; set; }
        public int Count { get; set; }
        public string Description { get; set; }
        public string NameFish { get; set; }
    
        public virtual Feeding Feeding { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fishing> Fishing { get; set; }
    }
}
