//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fishing2._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feeding
    {
        public int ID_Feeding { get; set; }
        public string FeederName { get; set; }
        public int Active_ID { get; set; }
    
        public virtual Active Active { get; set; }
    }
}
