//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fishing2._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class FishResult
    {
        public int ID_FishResult { get; set; }
        public int CountFish { get; set; }
        public int Fishing_ID { get; set; }
    
        public virtual Fishing Fishing { get; set; }
    }
}
